-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL U3225QE HHJXB34",
  mode = "3840x2160@60.00",
  position = "1440x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Display Corp. ATNA40HQ02-0",
  mode = "2880x1800@60.00",
  position = "0x0",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
