[global]
backend = "pulseaudio"
device_name = "laptop"
device_type = "computer"
bitrate = 320
initial_volume = 70
volume_controller = "softvol"
volume_normalisation = true
normalisation_pregain = -10
autoplay = true
use_mpris = true
cache_path = "/home/po/.cache/spotifyd"
max_cache_size = 1000000000
