# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = hyprctl dispatch workspace 1

# Autostart scripts and services
exec-once = uwsm app -- hyprsunset
exec-once = sleep 3; uwsm-app -- 1password --silent
exec-once = hyprland-monitor-attached ~/bin/hypr-monitor-toggle ~/bin/hypr-monitor-toggle
exec-once = hypr-monitor-toggle
# exec-once = bluetooth-headset-notify

# Autostart apps
exec-once = [workspace 1 silent] omarchy-launch-browser
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
