# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = sleep 3; uwsm-app -- 1password --silent
exec-once = /usr/bin/hyprland-monitor-attached $HOME/bin/hdmi/hdmi-connect.sh $HOME/bin/hdmi/hdmi-disconnect.sh
exec-once = uwsm app -- hyprsunset
