# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = hyprctl dispatch workspace 1

# Autostart scripts and services
exec-once = uwsm app -- hyprsunset
exec-once = uwsm-app -- easyeffects --service-mode
exec-once = sleep 3; uwsm-app -- 1password --silent
exec-once = hyprland-monitor-attached ~/bin/hypr-monitor-toggle ~/bin/hypr-monitor-toggle
exec = hypr-monitor-toggle # Also executed when hyprland reloads

# Autostart apps
exec-once = omarchy-launch-browser
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"

# Empty the trash once every day
exec-once = trash-empty 30
