# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"

bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"

bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private

bindd = SUPER SHIFT, C, Calendar Pouding, exec, omarchy-launch-or-focus-webapp Agenda "https://calendar.google.com/calendar/u/0/r"
bindd = SUPER SHIFT ALT, C, Calendar Rosemont, exec, omarchy-launch-or-focus-webapp Agenda "https://outlook.office.com/calendar/view/month"

bindd = SUPER SHIFT, E, Email Pouding, exec, omarchy-launch-or-focus-webapp "po@pouding.com" "https://mail.google.com/mail/u/0/##inbox"
bindd = SUPER SHIFT ALT, E, Email Code Rubik, exec, omarchy-launch-or-focus-webapp "pomartel@coderubik.com" "https://mail.google.com/mail/u/1/##inbox"
bindd = SUPER SHIFT CTRL, E, Email Rosemont, exec, omarchy-launch-or-focus-webapp Outlook "https://outlook.office.com/mail/0/"

bindd = SUPER SHIFT, F, File manager (Nautilus), exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT ALT, F, File manager (Yazi), exec, omarchy-launch-or-focus-tui yazi

bindd = SUPER SHIFT, G, Messenger, exec, omarchy-launch-or-focus-webapp Messenger "https://messenger.com"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

bindd = SUPER SHIFT, N, Neovim, exec, omarchy-launch-editor
bindd = SUPER SHIFT ALT, N, Visual Studio Code, exec, uwsm-app -- code

bindd = SUPER SHIFT, M, Music (Spotify), exec, omarchy-launch-or-focus spotify

bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"

bindd = SUPER SHIFT, P, Apple Photos, exec, omarchy-launch-or-focus-webapp "iCloud Photos" "https://www.icloud.com/photos/"

bindd = SUPER SHIFT, R, Apple Reminders, exec, omarchy-launch-or-focus-webapp "iCloud Reminders" "https://www.icloud.com/reminders/"

bindd = SUPER SHIFT, T, Microsoft Teams, exec, omarchy-launch-or-focus-webapp "Microsoft Teams" "https://teams.microsoft.com/v2/"

bindd = SUPER SHIFT, W, Typora, exec, omarchy-launch-or-focus Typora "uwsm-app -- typora --enable-wayland-ime"

bindd = SUPER SHIFT, X, 1Password, exec, uwsm-app -- 1password

bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"

unbind = SUPER, W
bindd = SUPER, Q, Close active window, killactive

# Utilities bindings
bindd = SUPER ALT, B, Bluetooth TUI, exec, omarchy-launch-bluetooth
bindd = SUPER ALT, L, Lock screen, exec, omarchy-lock-screen
bindd = SUPER ALT, P, HDMI Toggle, exec, "$HOME/bin/hdmi-toggle.sh"
bindd = SUPER ALT, T, Btop, exec, omarchy-launch-or-focus-tui btop
bindd = SUPER ALT, W, Wifi TUI, exec, omarchy-launch-wifi
bindd = SUPER ALT, X, 1Password Quick Access, exec, uwsm-app -- 1password --quick-access
