# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  kb_layout = ca
  kb_model= pc105
  kb_options = grp:alt_space_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  natural_scroll  = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  sensitivity = 0.1

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    tap-and-drag = false
    
    # Move windows with three-finger drag
    drag_3fg = 1

    # Use two-finger clicks for right-click instead of lower-right corner
    clickfinger_behavior = true

    # Control the speed of your scrolling
    # scroll_factor = 1.5
  }
}

# Configuration for the X1 Carbon trackpad
device {
  name = snsl0028:00-2c2f:0028-touchpad
  scroll_factor = 1.5
  
}

# Configuration for the X1 Carbon trackpoint
device {
  name = tpps/2-elan-trackpoint
  sensitivity = -0.5
}

# Scroll nicely in the terminal
windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)
windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace
