# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# X1 Carbon laptop monitor
monitor=desc:Samsung Display Corp. ATNA40HQ02-0, 2880x1800@120, auto, 2

# External monitor
# env = GDK_SCALE,1.75
monitor=desc:Dell Inc. DELL U3225QE HHJXB34,highrr, auto, 1.6

# External projector mirror setup (mirror laptop screen to projector)
monitor=HDMI-A-1,preferred,auto,auto,mirror,eDP-1

# Browser always on workspace 1
windowrulev2 = workspace 1,class:(brave-browser)

