# Tag to float and center a window
windowrule = float on, center on, match:tag centered-floating-window

# Keep dialogs centered and floating
windowrule = tag +centered-floating-window, match:title ^(Print|Imprimer|DesktopEditors)$
windowrule = tag +centered-floating-window, match:class ^(org.omarchy.nmtui-connect|nm-connection-editor)$
