# Floating windows
windowrule = tag +floating-window, match:class org.omarchy.nmtui-connect
windowrule = tag +floating-window, match:class nm-connection-editor

# Keep ONLYOFFICE dialogs cenetered.
windowrule = center on, match:class ^DesktopEditors$

# Keep Print dialogs centered and floating
windowrule = center on, match:title ^Print$
windowrule = float on, match:title ^Print$

