# Floating windows
windowrule = tag +floating-window, match:class org.omarchy.nmtui-connect
windowrule = tag +floating-window, match:class nm-connection-editor

# Brave Browser always on workspace 1
windowrule = workspace 1 silent, match:class ^(brave-browser)$
