personality = "pragmatic"
model = "gpt-5.4"
model_reasoning_effort = "medium"

[[skills.config]]
path = "/home/po/.config/codex/skills/.system/skill-creator/SKILL.md"
enabled = false

[projects."/home/po/Install"]
trust_level = "trusted"

[projects."/home/po/Work/omarchy"]
trust_level = "trusted"

[projects."/home/po/Work/sudomarchy"]
trust_level = "trusted"

[projects."/home/po/.config/uwsm"]
trust_level = "trusted"

[projects."/home/po/bin"]
trust_level = "trusted"

[projects."/home/po"]
trust_level = "trusted"

[projects."/home/po/.local/share/omarchy"]
trust_level = "trusted"

[tui]
notification_method = "osc9"
