[ids]
*

[main]
# Caps: tap = Esc, hold = Super+Shift
capslock = overload(supershift, esc)

# Maps the windows copilot key to f13
leftshift+leftmeta+f23 = f13
rightcontrol = f13

[altgr]
z = « 
x =  »

[supershift:M-S]
