[ids]
*

[main]
# Caps: tap = Esc, hold = Super+Shift
capslock = overload(supershift, esc)

# Maps the windows copilot key and insert key to f13
leftshift+leftmeta+f23 = f13
insert = f13

[supershift:M-S]



