# Remove the default config file and symlink it
# sudo rm /etc/keyd/default.conf
# sudo ln -s ~/.config/keyd/default.conf /etc/keyd/default.conf
# sudo systemctl restart keyd

[ids]
*

[main]
# Caps: tap = Esc, hold = Super+Shift
capslock = overload(supershift, esc)

# You can put other normal mappings here too...

[supershift:M-S]
